version: "3"

services:
  postgres:
    image: matthieuberger/postgres-multi-db:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_MULTIPLE_DATABASES=platform
    networks:
      - default

  temporal:
    restart: on-failure:3
    build:
      context: ./temporal
      dockerfile: Dockerfile
    ports:
      - 7233:7233
      - 8233:8233
    volumes:
      - ./tmp/teamporal:/usr/temporal/
  # react:
  #   build:
  #     context: ./webapp
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3001:3001
  #   networks:
  #     - default
  #   depends_on:
  #     - api

  # api:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile.api
  #   environment:
  #     - DB_HOST=postgres
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - postgres
  #   networks:
  #     - default
  # worker:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile.worker
  #   environment:
  #     - DB_HOST=postgres
  #     - TEMPORAL_HOST=temporal
  #     - NYLAS_API_KEY=nyk_v0_ku8lCMeP3fdwVrc5YAJ7X5ertUctbXuVrdmSEl2iWytqOIrWNRKh3xNVZ3pFlBN3
  #     - NYLAS_API_URL='https://api.eu.nylas.com'
  #   depends_on:
  #     - postgres
  #     - temporal
  #   networks:
  #     - default
  # client:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile.client
  #   environment:
  #     - DB_HOST=postgres
  #     - TEMPORAL_HOST=temporal
  #     - NYLAS_API_KEY=nyk_v0_ku8lCMeP3fdwVrc5YAJ7X5ertUctbXuVrdmSEl2iWytqOIrWNRKh3xNVZ3pFlBN3
  #     - NYLAS_API_URL='https://api.eu.nylas.com'
  #   depends_on:
  #     - postgres
  #     - temporal
  #     - worker
  #   networks:
  #     - default

networks:
  default:
    driver: bridge
    name: mentium-net
